### ISSUE TITLE
Warning due to resolve with clojurescript >= 1.9.660

### ISSUE THREAD

**Issue by pandeiro** [funcool/bide#11]
Now that `resolve` exists in `cljs.core`, the compiler emits a warning:

```
WARNING: resolve already refers to: cljs.core/resolve being replaced by: bide.core/resolve at line 121 /main.out/bide/core.cljs
```
Could this be fixed with a quick `(:refer-clojure :exclude [resolve])` in `bide.core`?

**Comment by niwinz** [comment]
This is already fixed
