### ISSUE TITLE
Warning when compiled with shadow-cljs: variable toString is undeclared

### ISSUE THREAD

**Issue by theasp** [funcool/bide#17]
The following warning is generated when compiling with [shadow-cljs](https://github.com/thheller/shadow-cljs), though everything seems to work fine otherwise.

```
------ WARNING #1 --------------------------------------------------------------
 File: bide/impl/helpers.js:29:41

 variable toString is undeclared
--------------------------------------------------------------------------------
```

https://github.com/funcool/bide/blob/master/src/bide/impl/helpers.js#L29

**Comment by niwinz** [comment]
I can't handle any unexpected error with not official compilers, please reproduce that warning with standard compiler.

**Comment by theasp** [comment]
Hi @niwinz,

I believe that the warning is correct, toString is not defined.  I think it should be using `Object.prototype.toString.call()`
