### ISSUE TITLE
Operation for replacing a URL without modifying history

### ISSUE THREAD

**Issue by ghost** [funcool/bide#2]
The function for navigating, `navigate!`, adds a new entry to the history and changes the URL. Would it make sense to have an alternative that doesn't add an entry to the history? Kind of how `pushState` and `replaceState` work in the [History](https://developer.mozilla.org/es/docs/Web/API/History) API.

**Comment by niwinz** [comment]
:+1: PR is welcome ;)

**Comment by niwinz** [comment]
It just can be a new function or an additional parameter to `navigate!`, I don't know that is the better solution

**Comment by niwinz** [comment]
Closed
