### ISSUE TITLE
Support for Clojure

### ISSUE THREAD

**Issue by piranha** [funcool/bide#4]
I like the syntax, so why not? I might take a stab at this later on. :)

**Comment by niwinz** [comment]
I like the idea!

**Comment by dustingetz** [comment]
Is there a fundamental design reason for the javascript impl?

**Comment by niwinz** [comment]
the time saving, just using an existing implementation

**Comment by niwinz** [comment]
Probably if someone wants a similar routing library that works in clj and cljs can try using https://github.com/metosin/reitit that seems nice.

bide is created because i want a simple solution for frontend routing, and in the time when this is created there wasnt any good solution.
